### ISSUE TITLE
Comparison with B-Method and Rodin

### ISSUE THREAD

**Issue by glyn** [magmide/magmide#3]
[B-Method](https://en.wikipedia.org/wiki/B-Method), like magma, aimed at correct code generation and was successfully used in several projects, as was the follow-on project [the Rodin tool](https://en.wikipedia.org/wiki/Rodin_tool).

I was involved in the development of a transactional logger using the B-Method. The implementation was sound, but the generated code was massively bloated and had to be hand-ported to produce a more compact implementation.

You may like to compare notes with this approach.

**Comment by blainehansen** [comment]
Excellent thank you again!

**Comment by blainehansen** [comment]
Closed by https://github.com/magmide/magmide/commit/f8642fb19851745089f2636e6cbfc07f31f1ac50

I did a fair amount of digging into these tools. Although I found it difficult to find a lot of information, I was able to get enough to get a sense of how it's designed.

There are two big reasons I think Magmide can avoid the problems you've brought up:

- It doesn't seem B-Method or Rodin used any kind of separation logic, referenced in the above commit. Separation logic can make it possible/ergonomic to reason directly about imperative code, rather than relying on code generation from some more "functional" language. This means you can write extremely compact and literal code, and then prove properties of it that are all "erased" when the code is compiled. This is also a core idea of the Coq's `Prop` type universe.
- The goal of the project is to (eventually :crossed_fingers:) end up with an end-to-end verified abstraction stack, one that rests directly on an axiomatic formalization of *hardware*, the lowest we can possibly go. This means it will be possible to verify not only the code we write, but all the optimizations and compilation that lowers the code to machine language. I think we could get much more ambitious about optimizations if we can actually certify both the algorithms and the implementations, avoiding problems like code bloat!

**Comment by programmerjake** [comment]
> * The goal of the project is to (eventually 🤞) end up with an end-to-end verified abstraction stack, one that rests directly on an axiomatic formalization of _hardware_, the lowest we can possibly go.

A little off-topic, but that's not the lowest we can go -- I'm working on a project where we have formal proofs of parts of the hardware (aka. does this ALU compute the right answer): https://libre-soc.org/

**Comment by blainehansen** [comment]
Ah yes you're absolutely right :) It would indeed be very cool to tie a set of hardware "axioms" to the actual hardware description language code that defines them!
