### ISSUE TITLE
Thoughts (if you *truly* wish to make this a practical language)

### ISSUE THREAD

**Issue by ckaran** [magmide/magmide#8]
If you *truly* want to make this a practical language, you're going to accept knots in your turing tape.  That is, if you assume all addressable memory is just an ordinary read/write cell, you'll have left out the richness (and weirdness) of memory.  Off the top of my head:

- Thread local storage
- Memory mapped I/O
- Memory mapping in general (IIRC, it's possible to tie a knot in memory; that is, map two virtual addresses to the same physical memory, so writing one range changes the other range, all within the same process)
- Read-only memory
- Write-only memory
- Pretty much anything involving GPU memory
- Memory alignment (if you want to do any systems programming, this will be an issue)

I suspect that means that you'll need a mechanism to not only describe attributes of a memory range, you'll need the mechanism to be able to operate over time.  Rust has dipped its toe into this, with the whole lifetimes syntax, but I suspect that is just the start.  For example, can you put dates and durations into the language?  If I have a CPU and a GPU, each of them running at slightly different clock rates, there needs to be some method of making them communicate (e.g., PCI, etc.) that can handle the mismatch.  

These are literally off the top of my head, there may be other issues as well, I just wanted to make certain that you *can* deal with them within Magmide.

**Comment by blainehansen** [comment]
I agree it's absolutely necessary for a memory model to be as accurate as possible! Not all projects need to concern themselves with this level of detail though. It's important to point out the Magmide design isn't really a "normal" language that most of us are used to dealing with. The *logical* dependently typed pure functional part is really the place where the power of the language rests. That logical component would be capable of defining any logical model you want (you can already define any logical model you're capable of in languages like Coq, it's just really difficult to use those models to metaprogrammatically assemble real code).

So yes all of these things are possible (you should read about separation logic and the "Iris from the ground up" paper to understand how even things like time-dependent memory requirements or access modes that can be changed by one process but not by others are all possible to model), and lower level code like operating systems would likely want to fully deal with all this complexity in order to provide higher level systems with verified abstractions.

I appreciate you bringing these thorny questions up :) I do however want to let you know that the *way* you've done so is kinda sharp and flippant and bordering on rude ha. I'll absolutely remember these points though!

**Comment by blainehansen** [comment]
Awesome thank you for being nice :) We all accidentally come in too hot sometimes ha

**Comment by ckaran** [comment]
It's my fault; I have a tendency to be quite abrupt in my speech and writing style, which has been an issue for me my whole life.  I normally re-read messages several times before I send them in an effort to avoid my normal lack of tact, but your project got me pretty excited, and I just kind of... did what I usually do.  Again, my apologies for offending you!
